// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SupermarketPlanner.Api.Infrastructure.Adapters.Driven.Persistence;

#nullable disable

namespace SupermarketPlanner.Api.Migrations
{
    [DbContext(typeof(SupermarketPlannerDbContext))]
    [Migration("20260620074121_InitialSchemaParity")]
    partial class InitialSchemaParity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SupermarketPlanner.Api.Infrastructure.Adapters.Driven.Persistence.ActiveCartEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp(3)")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ActiveCart", (string)null);
                });

            modelBuilder.Entity("SupermarketPlanner.Api.Infrastructure.Adapters.Driven.Persistence.ActiveCartItemEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CartId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cartId");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<double>("PricePerUnit")
                        .HasColumnType("double precision")
                        .HasColumnName("pricePerUnit");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("productId");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("productName");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Supermarket")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supermarket");

                    b.Property<string>("TaxType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("taxType");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("CartId", "Supermarket", "ProductName")
                        .IsUnique();

                    b.ToTable("ActiveCartItem", (string)null);
                });

            modelBuilder.Entity("SupermarketPlanner.Api.Infrastructure.Adapters.Driven.Persistence.PostalCodeEntity", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("ZoneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zoneId");

                    b.HasKey("Code");

                    b.HasIndex("ZoneId");

                    b.ToTable("PostalCode", (string)null);
                });

            modelBuilder.Entity("SupermarketPlanner.Api.Infrastructure.Adapters.Driven.Persistence.PricingZoneEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("PricingZone", (string)null);
                });

            modelBuilder.Entity("SupermarketPlanner.Api.Infrastructure.Adapters.Driven.Persistence.ProductCategoryCacheEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3)")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalizedName");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("ProductCategoryCache", (string)null);
                });

            modelBuilder.Entity("SupermarketPlanner.Api.Infrastructure.Adapters.Driven.Persistence.ProductEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<string>("Supermarket")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supermarket");

                    b.Property<string>("TaxType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("taxType");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.HasIndex("Supermarket");

                    b.HasIndex("Supermarket", "Sku")
                        .IsUnique();

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("SupermarketPlanner.Api.Infrastructure.Adapters.Driven.Persistence.ProductPriceEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<double>("PricePerUnit")
                        .HasColumnType("double precision")
                        .HasColumnName("pricePerUnit");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("productId");

                    b.Property<DateTime>("ScrapedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3)")
                        .HasColumnName("scrapedAt")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ZoneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zoneId");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ZoneId");

                    b.HasIndex("ProductId", "ZoneId")
                        .IsUnique();

                    b.ToTable("ProductPrice", (string)null);
                });

            modelBuilder.Entity("SupermarketPlanner.Api.Infrastructure.Adapters.Driven.Persistence.ShoppingSessionEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3)")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ShoppedAt")
                        .HasColumnType("timestamp(3)")
                        .HasColumnName("shoppedAt");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("double precision")
                        .HasColumnName("totalPrice");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("ShoppedAt");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingSession", (string)null);
                });

            modelBuilder.Entity("SupermarketPlanner.Api.Infrastructure.Adapters.Driven.Persistence.ShoppingSessionItemEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<double>("PricePerUnit")
                        .HasColumnType("double precision")
                        .HasColumnName("pricePerUnit");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("productName");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sessionId");

                    b.Property<string>("Supermarket")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supermarket");

                    b.Property<string>("TaxType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("taxType");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("ShoppingSessionItem", (string)null);
                });

            modelBuilder.Entity("SupermarketPlanner.Api.Infrastructure.Adapters.Driven.Persistence.ZoneOnboardingQueueEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3)")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("errorMessage");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postalCode");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp(3)")
                        .HasColumnName("processedAt");

                    b.Property<string>("RequestedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("requestedByUserId");

                    b.Property<DateTime>("RequestedDay")
                        .HasColumnType("timestamp(3)")
                        .HasColumnName("requestedDay");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp(3)")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("PostalCode");

                    b.HasIndex("PostalCode", "RequestedDay")
                        .IsUnique();

                    b.HasIndex("State", "RequestedDay");

                    b.ToTable("ZoneOnboardingQueue", (string)null);
                });

            modelBuilder.Entity("SupermarketPlanner.Api.Infrastructure.Adapters.Driven.Persistence.ActiveCartItemEntity", b =>
                {
                    b.HasOne("SupermarketPlanner.Api.Infrastructure.Adapters.Driven.Persistence.ActiveCartEntity", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("SupermarketPlanner.Api.Infrastructure.Adapters.Driven.Persistence.PostalCodeEntity", b =>
                {
                    b.HasOne("SupermarketPlanner.Api.Infrastructure.Adapters.Driven.Persistence.PricingZoneEntity", "Zone")
                        .WithMany("PostalCodes")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("SupermarketPlanner.Api.Infrastructure.Adapters.Driven.Persistence.ProductPriceEntity", b =>
                {
                    b.HasOne("SupermarketPlanner.Api.Infrastructure.Adapters.Driven.Persistence.ProductEntity", "Product")
                        .WithMany("Prices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupermarketPlanner.Api.Infrastructure.Adapters.Driven.Persistence.PricingZoneEntity", "Zone")
                        .WithMany("Prices")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("SupermarketPlanner.Api.Infrastructure.Adapters.Driven.Persistence.ShoppingSessionItemEntity", b =>
                {
                    b.HasOne("SupermarketPlanner.Api.Infrastructure.Adapters.Driven.Persistence.ShoppingSessionEntity", "Session")
                        .WithMany("Items")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SupermarketPlanner.Api.Infrastructure.Adapters.Driven.Persistence.ActiveCartEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SupermarketPlanner.Api.Infrastructure.Adapters.Driven.Persistence.PricingZoneEntity", b =>
                {
                    b.Navigation("PostalCodes");

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("SupermarketPlanner.Api.Infrastructure.Adapters.Driven.Persistence.ProductEntity", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("SupermarketPlanner.Api.Infrastructure.Adapters.Driven.Persistence.ShoppingSessionEntity", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
